# FastAPI Backend Service
services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.api:SalesAPI().app --host 0.0.0.0 --port 8000"
    plan: free  # Choose an appropriate plan
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8000"
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: "/health/"
    regions: oregon  # Select your preferred region

  # Streamlit Frontend Service
  - type: web
    name: streamlit-frontend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0"
    plan: free  # Choose an appropriate plan
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8501"
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: "/"
    regions: oregon  # Select your preferred region
