version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the single Dockerfile
    ports:
      - "8000:8000"  # Map port for FastAPI
      - "8501:8501"  # Map port for Streamlit
    volumes:
      - ./app/backend:/app/backend  # Optional: Map the backend directory
      - ./app/frontend:/app/frontend  # Optional: Map the frontend directory
    environment:
      - PYTHONUNBUFFERED=1  # Ensure logs are printed in real-time
      - FASTAPI_URL=http://localhost:8000  # Point to FastAPI service
