version: '3.8'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app  # Maps the app folder from host to container
    environment:
      - PYTHONUNBUFFERED=1
