version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi  # Use the Dockerfile for FastAPI
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  # Maps the app folder from host to container
    environment:
      - PYTHONUNBUFFERED=1

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit  # Use the Dockerfile for Streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app  # Maps the app folder from host to container
    environment:
      - PYTHONUNBUFFERED=1
