services:
  fastapi-backend:
    build:
      context: .  # Set context to the root of the project
      dockerfile: app/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  streamlit-frontend:
    build:
      context: .  # Set context to the root of the project
      dockerfile: app/frontend/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/"]
      interval: 30s
      timeout: 10s
      retries: 3
