version: 1

services:
  fastapi-backend:
    type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"  # Pointing to the root requirements.txt
    startCommand: "uvicorn app.backend.main:api --host 0.0.0.0 --port 10000"  # Reference the 'api' instance
    healthCheckPath: /health/
    envVars:
      PORT: 10000

  streamlit-frontend:
    type: web
    name: streamlit-frontend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"  # Using the same root requirements.txt
    startCommand: "streamlit run app/frontend/app.py --server.port 10001 --server.address 0.0.0.0"
    envVars:
      PORT: 10001
