# Render configuration for FastAPI Backend and Streamlit Frontend

services:
  - type: web
    name: fastapi-backend
    env: docker
    buildCommand: "pip install -r requirements.txt"  # Install dependencies
    startCommand: "uvicorn backend.api:SalesAPI --host 0.0.0.0 --port 8000"  # Start FastAPI
    plan: free  # Choose an appropriate plan
    autoDeploy: true  # Enable auto-deployment on changes
    envVars:  # Environment variables
      - key: PORT
        value: "8000"  # Port to run the FastAPI app
      - key: PYTHONUNBUFFERED
        value: "1"  # Ensure logs are output in real-time
    healthCheckPath: "/health/"  # Health check endpoint
    regions: oregon  # Preferred region
    dockerfilePath: "app/backend/Dockerfile"  # Path to the backend Dockerfile

  - type: web
    name: streamlit-frontend
    env: docker  # Docker environment for the Streamlit app
    buildCommand: "pip install -r requirements.txt"  # Install dependencies
    startCommand: "streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0"  # Updated to use the correct app.py path
    plan: free  # Choose an appropriate plan
    autoDeploy: true  # Enable auto-deployment on changes
    envVars:  # Environment variables
      - key: PORT
        value: "8501"  # Port to run the Streamlit app
      - key: PYTHONUNBUFFERED
        value: "1"  # Ensure logs are output in real-time
    healthCheckPath: "/health"  # Health check endpoint
    regions: oregon  # Preferred region
    dockerfilePath: "app/frontend/Dockerfile"  # Path to the frontend Dockerfile

# Networking settings to allow the Streamlit app to access the FastAPI app
  - type: web
    name: api-network
    plan: free
    autoDeploy: true
    regions: oregon
    env: docker
    healthCheckPath: "/health/"
